[tools]
# https://mise-tools.jdx.dev/tools/opa
opa = "1.17.0"
# https://mise-tools.jdx.dev/tools/bun
bun = "1.3.14"
# https://mise-tools.jdx.dev/tools/shfmt
shfmt = "3.13.1"
# https://mise-tools.jdx.dev/tools/regal
regal = "0.40.0"
# https://mise-tools.jdx.dev/tools/lefthook
lefthook = "2.1.9"
# https://mise-tools.jdx.dev/tools/shellcheck
shellcheck = "0.11.0"
# https://mise-tools.jdx.dev/tools/golangci-lint
golangci-lint = "2.12.2"
# https://github.com/charmbracelet/vhs/releases
"github:charmbracelet/vhs" = "0.11.0"
# https://github.com/perplexityai/bumblebee/releases
"github:perplexityai/bumblebee" = "0.1.1"
