[tools]
# https://mise-tools.jdx.dev/tools/opa
opa = "latest"
# https://mise-tools.jdx.dev/tools/bun
bun = "1.3.11"
# https://mise-tools.jdx.dev/tools/regal
regal = "0.39.0"
# https://mise-tools.jdx.dev/tools/lefthook
lefthook = "2.1.4"
# https://mise-tools.jdx.dev/tools/golangci-lint
golangci-lint = "2.11.4"

[tasks."opa:fmt"]
description = "format opa files"
run = "opa fmt -w ./rules/policies"

[tasks."opa:lint"]
description = "lint opa files"
run = "regal lint ./rules/policies"

[tasks."opa:fix"]
description = "lint opa files"
run = "regal fix ./rules/policies"
